version: "3.9"

services:
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile
#    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    command: python3 manage.py runserver
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:5

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    command: celery -A app worker -l info
    depends_on:
      - redis

  celery_scheduler:
    container_name: celery_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    command: celery -A app beat -l info
    depends_on:
      - celery_worker

  db:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
#  static_volume:
#  media_volume: