version: "3.9"

services:
  web_prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src/data:/code/data
    env_file:
      - ./.env.prod
      - ./.env.db
    depends_on:
      - db

  redis:
    container_name: redis
    image: redis:5

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - celery_volume:/code
    command: celery -A app worker -l info
    env_file:
      - ./.env.prod
      - ./.env.db
    depends_on:
      - redis

  celery_scheduler:
    container_name: celery_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - celery_volume:/code
    command: celery -A app beat -l info
    env_file:
      - ./.env.prod
      - ./.env.db
    depends_on:
      - celery_worker

  db:
    restart: always
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  celery_volume: {}